version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'sleep 3 && npm start'
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/app:/app"
      
  caddy:
    image: caddy:latest
    ports:
      - "443:443"
      - "80:80"
    volumes: 
      - ${PWD}/services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

