version: "3"

services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    image: "paulfirst/devops-for-programmers-project-lvl1_app_1:latest"
    depends_on: 
      - db

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes: 
      - db:/var/lib/postgresql/data
      
volumes:
  db:
    driver: local
