version: "3.7"

services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    image: "paulfirst/devops-for-programmers-project-lvl1_app_1:latest"
    depends_on: 
      db:
        condition: service_healthy
    env_file:
      - ./app/.env.example

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
