
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/app:/app"
      
  caddy:
    image: caddy:2.5.1-alpine
    ports:
      - "443:443"
      - "80:80"
    volumes: 
      - ${PWD}/services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

